settings:
  digits: 3
  prefix: SOUPTC
  sep: ''
  itemformat: markdown
  parent: SOUP
attributes:
  defaults:
    doc:
      title: RustyCAN — SOUP Test Cases
      copyright: RustyCAN
    method: manual
    test-command: ''
  reviewed:
    - method
  publish:
    - method
    - test-command
