//! KCAN EP0 vendor request handler.
//!
//! Responds to the control sequence the host KCAN adapter issues on every
//! connect before bulk traffic can start:
//!
//! ```text
//! Host → GET_INFO      (0x01)  device responds with firmware version + UID
//! Host → GET_BT_CONST  (0x06)  device responds with clock / BRP / TSEG limits
//! Host → SET_BITTIMING (0x02)  host sends computed BRP/TSEG for chosen bitrate
//! Host → SET_MODE      (0x04)  host sends bus-on / listen-only flags
//! ```
//!
//! Without this handler `KCanAdapter::open()` fails immediately with
//! `"GET_INFO: short response"` and no bulk traffic flows.
//!
//! This handler also drives [`crate::usb_task::USB_CONFIGURED`] on connect /
//! disconnect (replacing the old `UsbStateHandler`), so only one handler needs
//! to be registered with the USB builder.

use embassy_usb::control::{InResponse, OutResponse, Recipient, Request, RequestType};
use embassy_usb::Handler;

use kcan_protocol::control::{
    KCanBitTiming, KCanBtConst, KCanDeviceInfo, KCanFdConfig, KCanMode, KCanModeFdFlags,
    KCanModeFlags, RequestCode,
};

use defmt::*;

// Firmware version constants generated by build.rs from Cargo.toml.
mod version {
    include!(concat!(env!("OUT_DIR"), "/version_consts.rs"));
}

// ─── Pending bit-timing storage ───────────────────────────────────────────────
// The host sends SET_BITTIMING and (optionally) SET_FD_BITTIMING before
// SET_MODE(BUS_ON).  We store them here so SET_MODE can assemble the full
// KCanFdConfig and signal CAN_CONFIG to can_task.
use core::cell::Cell;
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::blocking_mutex::Mutex;

static PENDING_NOMINAL_BT: Mutex<CriticalSectionRawMutex, Cell<Option<KCanBitTiming>>> =
    Mutex::new(Cell::new(None));

static PENDING_FD_BT: Mutex<CriticalSectionRawMutex, Cell<Option<KCanBitTiming>>> =
    Mutex::new(Cell::new(None));

/// EP0 vendor handler: responds to GET_INFO / GET_BT_CONST and ACKs
/// SET_BITTIMING / SET_MODE.  Also signals USB connection state.
pub struct KCanEp0Handler {
    pub uid_lo: u32,
}

impl Handler for KCanEp0Handler {
    fn suspended(&mut self, suspended: bool) {
        if suspended {
            // VBUS loss (cable pull) triggers a USB suspend with ULPI PHY.
            // configured(false) does NOT fire on VBUS loss — suspend is the
            // only reliable signal.
            info!("USB: suspended (cable disconnected)");
            lcd_terminal::boot_log!(
                crate::display_task::LOG_CHANNEL,
                "USB cable disconnected",
                lcd_terminal::BootStatus::Warn
            );
            crate::display_task::USB_STATUS
                .signal(crate::display_task::UsbDisplayStatus::Disconnected);
            crate::usb_task::USB_CONFIGURED.signal(false);
            crate::usb_task::USB_CONFIGURED_LED.signal(false);
        }
        // On resume, configured() fires again if still connected — no action needed.
    }

    fn configured(&mut self, configured: bool) {
        if configured {
            info!("USB: configured by host");
            lcd_terminal::boot_log!(
                crate::display_task::LOG_CHANNEL,
                "USB host connected (enumerated)",
                lcd_terminal::BootStatus::Ok
            );
            crate::display_task::USB_STATUS
                .signal(crate::display_task::UsbDisplayStatus::HostConnected);
        } else {
            info!("USB: disconnected / reset");
            // Note: this may not fire on physical VBUS loss with ULPI PHY.
            // Cable disconnect is also handled by kcan_io_task (EndpointError::Disabled).
            crate::display_task::USB_STATUS
                .signal(crate::display_task::UsbDisplayStatus::Disconnected);
        }
        crate::usb_task::USB_CONFIGURED.signal(configured);
        crate::usb_task::USB_CONFIGURED_LED.signal(configured);
    }

    fn control_in<'a>(&'a mut self, req: Request, buf: &'a mut [u8]) -> Option<InResponse<'a>> {
        // Only intercept vendor requests directed at the device.
        if req.request_type != RequestType::Vendor || req.recipient != Recipient::Device {
            return None;
        }

        match req.request {
            r if r == RequestCode::GetInfo as u8 => {
                let mut info = KCanDeviceInfo::new(
                    version::FW_MAJ,
                    version::FW_MIN,
                    version::FW_PAT,
                    self.uid_lo,
                );
                // H743 has one physical CAN channel: FDCAN1 → TJA1044 → CN3 DB9.
                info.channels = 1;
                let bytes = info.to_bytes();
                let len = bytes.len().min(buf.len());
                buf[..len].copy_from_slice(&bytes[..len]);
                info!(
                    "EP0 GET_INFO → protocol_v1, channels=1, uid={:08X}",
                    self.uid_lo
                );
                Some(InResponse::Accepted(&buf[..len]))
            }
            r if r == RequestCode::GetBtConst as u8 => {
                let bytes = KCanBtConst::H743_32MHZ.to_bytes();
                let len = bytes.len().min(buf.len());
                buf[..len].copy_from_slice(&bytes[..len]);
                info!("EP0 GET_BT_CONST → clock=32 MHz, BRP 1-512");
                Some(InResponse::Accepted(&buf[..len]))
            }
            _ => None,
        }
    }

    fn control_out(&mut self, req: Request, _data: &[u8]) -> Option<OutResponse> {
        // Only intercept vendor requests directed at the device.
        if req.request_type != RequestType::Vendor || req.recipient != Recipient::Device {
            return None;
        }

        match req.request {
            r if r == RequestCode::SetBitTiming as u8 => {
                // Decode the timing payload to derive the actual bitrate and
                // display it on the LCD stats row.
                // Formula: bitrate = clock_hz / (BRP × (1 + TSEG1 + TSEG2))
                if let Some(bt) = _data
                    .get(..16)
                    .and_then(|s| <&[u8; 16]>::try_from(s).ok())
                    .map(KCanBitTiming::from_bytes)
                {
                    let tq = 1 + bt.tseg1 + bt.tseg2;
                    if bt.brp > 0 && tq > 0 {
                        let kbps = KCanBtConst::H743_32MHZ.clock_hz / (bt.brp * tq) / 1_000;
                        crate::display_task::BAUD_KBPS
                            .store(kbps, core::sync::atomic::Ordering::Relaxed);
                        info!("EP0 SET_BITTIMING → {} kbps", kbps);
                    }
                    PENDING_NOMINAL_BT.lock(|c| c.set(Some(bt)));
                } else {
                    info!("EP0 SET_BITTIMING accepted (no payload)");
                }
                Some(OutResponse::Accepted)
            }
            r if r == RequestCode::SetFdBitTiming as u8 => {
                if let Some(bt) = _data
                    .get(..16)
                    .and_then(|s| <&[u8; 16]>::try_from(s).ok())
                    .map(KCanBitTiming::from_bytes)
                {
                    // Copy fields to locals — KCanBitTiming is repr(C, packed)
                    // and taking references to its fields is UB in safe Rust.
                    let (brp, tseg1, tseg2, sjw) = (bt.brp, bt.tseg1, bt.tseg2, bt.sjw);
                    info!(
                        "EP0 SET_FD_BITTIMING → BRP={} TSEG1={} TSEG2={} SJW={}",
                        brp, tseg1, tseg2, sjw
                    );
                    PENDING_FD_BT.lock(|c| c.set(Some(bt)));
                } else {
                    info!("EP0 SET_FD_BITTIMING accepted (no payload)");
                }
                Some(OutResponse::Accepted)
            }
            r if r == RequestCode::SetMode as u8 => {
                // Parse the mode payload.
                let (flags, fd_flags) = if _data.len() >= 4 {
                    let arr: [u8; 4] = _data[..4].try_into().unwrap();
                    let m = KCanMode::from_bytes(&arr);
                    (m.flags, m.fd_flags)
                } else if !_data.is_empty() {
                    (_data[0], 0u8)
                } else {
                    (0u8, 0u8)
                };

                if flags & KCanModeFlags::BUS_OFF != 0 {
                    // Host app closed — revert circle to amber.
                    info!("EP0 SET_MODE bus-off (app closed)");
                    crate::usb_task::LISTEN_ONLY
                        .store(false, core::sync::atomic::Ordering::Relaxed);
                    lcd_terminal::boot_log!(
                        crate::display_task::LOG_CHANNEL,
                        "RustyCAN closed CAN port",
                        lcd_terminal::BootStatus::Warn
                    );
                    crate::display_task::USB_STATUS
                        .signal(crate::display_task::UsbDisplayStatus::HostConnected);
                } else {
                    // BUS_ON — app just opened.
                    let listen_only = flags & KCanModeFlags::LISTEN_ONLY != 0;
                    crate::usb_task::LISTEN_ONLY
                        .store(listen_only, core::sync::atomic::Ordering::Relaxed);

                    // Assemble CAN_CONFIG from previously stored bit-timing values.
                    let nominal_baud = PENDING_NOMINAL_BT
                        .lock(|c| c.get())
                        .and_then(|bt| {
                            let tq = 1 + bt.tseg1 + bt.tseg2;
                            if bt.brp > 0 && tq > 0 {
                                Some(KCanBtConst::H743_32MHZ.clock_hz / (bt.brp * tq))
                            } else {
                                None
                            }
                        })
                        .unwrap_or(250_000);

                    let fd_enabled = fd_flags & KCanModeFdFlags::FD_ENABLED != 0;
                    let fd_timing = if fd_enabled {
                        PENDING_FD_BT.lock(|c| c.get())
                    } else {
                        None
                    };
                    let iso = fd_flags & KCanModeFdFlags::NON_ISO == 0;

                    crate::usb_task::CAN_CONFIG.signal(KCanFdConfig {
                        nominal_baud,
                        fd_timing,
                        iso,
                        mode_flags: flags,
                    });

                    if listen_only {
                        info!(
                            "EP0 SET_MODE bus-on (listen-only, {} bps, fd={})",
                            nominal_baud, fd_enabled
                        );
                        lcd_terminal::boot_log!(
                            crate::display_task::LOG_CHANNEL,
                            "RustyCAN app opened CAN port (listen-only)",
                            lcd_terminal::BootStatus::Ok
                        );
                        crate::display_task::USB_STATUS
                            .signal(crate::display_task::UsbDisplayStatus::AppConnectedListenOnly);
                    } else {
                        info!(
                            "EP0 SET_MODE bus-on ({} bps, fd={})",
                            nominal_baud, fd_enabled
                        );
                        lcd_terminal::boot_log!(
                            crate::display_task::LOG_CHANNEL,
                            "RustyCAN app opened CAN port",
                            lcd_terminal::BootStatus::Ok
                        );
                        crate::display_task::USB_STATUS
                            .signal(crate::display_task::UsbDisplayStatus::AppConnected);
                    }
                    // Signal the IO task that a new host session is starting.
                    crate::usb_task::BULK_RESTART.signal(());
                }
                Some(OutResponse::Accepted)
            }
            _ => None,
        }
    }
}
