//! KCAN bootloader for STM32H753ZI (Nucleo-H753ZI).
//!
//! Identical logic to bootloader-h743; differences:
//! * MCU: `stm32h753zi` (same Cortex-M7 core, adds TDES/AES/HASH)
//! * USB: OTG-FS (PA11/PA12), no ULPI PHY — Nucleo uses the embedded FS PHY
//! * D_SEL pin (PB14): pull low for 12.5 ms before enabling USB to meet SDIS
//!   requirement on boards with USB bypass capacitor
//!
//! # Flash layout — same as H743
//! ```text
//! 0x08000000  Bootloader (128 KB)  ← this binary
//! 0x08020000  Active App (896 KB)
//! 0x08100000  STATE      (128 KB)
//! 0x08120000  DFU        (896 KB)
//! ```

#![no_std]
#![no_main]

use embassy_boot::{AlignedBuffer, BlockingFirmwareUpdater, FirmwareUpdaterConfig};
use embassy_boot_stm32::BootLoader;
use embassy_executor::Spawner;
use embassy_stm32::flash::{Blocking, Flash};
use embassy_stm32::gpio::{Level, Output, Speed};
use embassy_stm32::time::Hertz;
use embassy_stm32::usb::Driver;
use embassy_stm32::{bind_interrupts, peripherals, usb, Config};
use embassy_sync::blocking_mutex::raw::NoopRawMutex;
use embassy_sync::blocking_mutex::Mutex;
use embassy_usb::Builder as UsbBuilder;
use embassy_usb_dfu::consts::DfuAttributes;
use embassy_usb_dfu::dfu::new_state;
use embassy_usb_dfu::ResetImmediate;

use core::cell::RefCell;
use defmt::*;
use defmt_rtt as _;
use panic_probe as _;

bind_interrupts!(struct Irqs {
    OTG_FS => usb::InterruptHandler<peripherals::USB_OTG_FS>;
});

// STM32H7 flash write size is 32 bytes (256-bit word).
// Used for the STATE aligned buffer passed to BlockingFirmwareUpdater.
const FLASH_WRITE_SIZE: usize = 32;
// DFU USB transfer block size — must be a multiple of FLASH_WRITE_SIZE.
// 64 bytes matches dfu-util's minimum transfer size and the host's DFU_BLOCK_SIZE.
const DFU_BLOCK_SIZE: usize = 64;

static PUBLIC_KEY: [u8; 32] = *include_bytes!("../../signing-pubkey.bin");

// Bootloader version constants (BL_MAJ, BL_MIN, BL_PAT) — generated by build.rs.
mod version {
    include!(concat!(env!("OUT_DIR"), "/version_consts.rs"));
}

static mut CONFIG_DESC: [u8; 256] = [0u8; 256];
static mut BOS_DESC: [u8; 256] = [0u8; 256];
static mut MSOS_DESC: [u8; 256] = [0u8; 256];
static mut CTRL_BUF: [u8; 64] = [0u8; 64];
static mut USB_EP_OUT_BUF: [u8; 1024] = [0u8; 1024];

#[embassy_executor::main]
async fn main(_spawner: Spawner) {
    unsafe {
        let mut cp = cortex_m::peripheral::Peripherals::steal();
        cp.SCB.disable_dcache(&mut cp.CPUID);
    }

    let mut config = Config::default();
    {
        use embassy_stm32::rcc::*;
        config.rcc.hse = Some(Hse {
            freq: Hertz(8_000_000), // Nucleo HSE is 8 MHz
            mode: HseMode::Oscillator,
        });
        config.rcc.pll1 = Some(Pll {
            source: PllSource::HSE,
            prediv: PllPreDiv::DIV2,
            mul: PllMul::MUL120,
            divp: Some(PllDiv::DIV2),
            divq: None,
            divr: None,
        });
        config.rcc.sys = Sysclk::PLL1_P;
        config.rcc.ahb_pre = AHBPrescaler::DIV2;
        config.rcc.apb1_pre = APBPrescaler::DIV2;
        config.rcc.apb2_pre = APBPrescaler::DIV2;
        config.rcc.apb3_pre = APBPrescaler::DIV2;
        config.rcc.apb4_pre = APBPrescaler::DIV2;
        config.rcc.voltage_scale = VoltageScale::Scale1;
        config.rcc.csi = true;
        config.rcc.hsi48 = Some(Hsi48Config {
            sync_from_usb: false,
        });
        config.rcc.mux.usbsel = mux::Usbsel::HSI48;
    }
    let p = embassy_stm32::init(config);

    let mut led = Output::new(p.PB14, Level::High, Speed::Low); // LD3 yellow (PB14 doubles as SDIS)

    // ── SDIS pull-low (~13 ms) for Nucleo USB bypass capacitor ───────────────
    // PB14 = LD3 (yellow) also drives SDIS. Hold low to discharge the bypass
    // capacitor before enabling USB. At 240 MHz (after AHB/2): 240e6/2 * 0.013
    // ≈ 1_560_000 cycles.
    led.set_low();
    cortex_m::asm::delay(1_560_000);

    // ── Flash and embassy-boot ─────────────────────────────────────────────────
    let flash = Flash::new_blocking(p.FLASH);
    let flash_mutex: Mutex<NoopRawMutex, RefCell<Flash<'_, Blocking>>> =
        Mutex::new(RefCell::new(flash));

    {
        use embassy_boot::State;
        use embassy_boot_stm32::BootLoaderConfig;
        let bl_config =
            BootLoaderConfig::from_linkerfile_blocking(&flash_mutex, &flash_mutex, &flash_mutex);
        let bl = BootLoader::prepare::<_, _, _, FLASH_WRITE_SIZE>(bl_config);
        info!("BootLoader state after prepare: {:?}", bl.state);

        if bl.state != State::DfuDetach {
            info!("Jumping to app at 0x08020000");
            // Stamp the bootloader version into RTC backup registers before the
            // jump so the app can read and display it.
            // BKP1R: packed version  (major<<16 | minor<<8 | patch)
            // BKP2R: sentinel 0xB007_B007 confirming a valid bootloader handoff
            {
                use embassy_stm32::pac;
                pac::PWR.cr1().modify(|w| w.set_dbp(true));
                let v = (version::BL_MAJ as u32) << 16
                    | (version::BL_MIN as u32) << 8
                    | version::BL_PAT as u32;
                pac::RTC.bkpr(1).write(|w| w.set_bkp(v));
                pac::RTC.bkpr(2).write(|w| w.set_bkp(0xB007_B007));
            }
            led.set_low();
            // SAFETY: app is a valid Cortex-M image at the Active partition start.
            unsafe { bl.load(0x08020000) }
        }
    }

    info!("Entering USB DFU download mode (FS)");
    led.set_high(); // LED on = DFU mode

    let updater_config =
        FirmwareUpdaterConfig::from_linkerfile_blocking(&flash_mutex, &flash_mutex);
    let mut aligned = AlignedBuffer([0u8; FLASH_WRITE_SIZE]);
    let updater = BlockingFirmwareUpdater::new(updater_config, aligned.as_mut());

    // OTG FS (PA11 = DM, PA12 = DP, embedded FS PHY, no ULPI)
    let mut usb_cfg = embassy_stm32::usb::Config::default();
    usb_cfg.vbus_detection = false;
    let driver = Driver::new_fs(
        p.USB_OTG_FS,
        Irqs,
        p.PA12, // DP
        p.PA11, // DM
        unsafe { &mut *core::ptr::addr_of_mut!(USB_EP_OUT_BUF) },
        usb_cfg,
    );

    let mut usb_config = embassy_usb::Config::new(0x1209, 0xBEEF);
    usb_config.manufacturer = Some("Kodezine");
    usb_config.product = Some("KCAN DFU H753");
    usb_config.serial_number = Some("00000000");
    usb_config.max_power = 100;
    usb_config.max_packet_size_0 = 64;
    usb_config.composite_with_iads = false;
    usb_config.device_class = 0xFE; // Application Specific
    usb_config.device_sub_class = 0x01; // Device Firmware Upgrade
    usb_config.device_protocol = 0x02; // DFU mode

    // DFU state must outlive the builder.
    let mut dfu_state = new_state::<_, _, _, DFU_BLOCK_SIZE>(
        updater,
        DfuAttributes::CAN_DOWNLOAD, // No MANIFESTATION_TOLERANT — device resets via ResetImmediate after flash
        ResetImmediate,
        &PUBLIC_KEY,
    );

    // SAFETY: static mut buffers, main() runs once, no other references.
    let mut builder = unsafe {
        UsbBuilder::new(
            driver,
            usb_config,
            &mut *core::ptr::addr_of_mut!(CONFIG_DESC),
            &mut *core::ptr::addr_of_mut!(BOS_DESC),
            &mut *core::ptr::addr_of_mut!(MSOS_DESC),
            &mut *core::ptr::addr_of_mut!(CTRL_BUF),
        )
    };

    embassy_usb_dfu::dfu::usb_dfu(&mut builder, &mut dfu_state, |_| {});

    let mut usb = builder.build();

    info!("USB DFU: waiting for host to send firmware");
    usb.run().await;
}
