//! KCAN bootloader for STM32H743XI (STM32H743I-EVAL MB1246 Rev E).
//!
//! # Role
//!
//! This binary runs from Bank1 sector 0 (0x08000000, 128 KB).
//! On every power-on it checks whether:
//!
//! 1. A firmware update was staged in the DFU partition (0x08120000, 896 KB),
//!    verified against the Ed25519 public key compiled into this binary.
//!    If verified → swap DFU→Active (0x08020000) and reboot into the new app.
//!
//! 2. The Active partition holds an unconfirmed image (app hasn't called
//!    `mark_booted()` since the last swap).  If so → revert the swap and
//!    boot the previous good image.  This is the rollback safety net.
//!
//! 3. Normal boot → jump to the Active partition at 0x08020000.
//!
//! # USB DFU mode
//!
//! The app firmware exposes a DFU Runtime interface.  When the host sends a
//! DFU_DETACH request, the app writes a magic value via `BlockingFirmwareState`
//! and resets.  On the next boot this bootloader detects the staged state and
//! starts the USB DFU download mode, accepting the signed binary from the host.
//!
//! # Flash layout
//! ```text
//! 0x08000000  Bootloader (128 KB — Bank1 sector 0)  ← this binary
//! 0x08020000  Active App (896 KB — Bank1 sectors 1–7)
//! 0x08100000  STATE      (128 KB — Bank2 sector 0)
//! 0x08120000  DFU        (896 KB — Bank2 sectors 1–7)
//! ```

#![no_std]
#![no_main]

use embassy_boot::{AlignedBuffer, BlockingFirmwareUpdater, FirmwareUpdaterConfig};
use embassy_boot_stm32::BootLoader;
use embassy_executor::Spawner;
use embassy_stm32::flash::{Blocking, Flash};
use embassy_stm32::gpio::{Level, Output, Speed};
use embassy_stm32::usb::Driver;
use embassy_stm32::{bind_interrupts, peripherals, usb, Config};
use embassy_sync::blocking_mutex::raw::NoopRawMutex;
use embassy_sync::blocking_mutex::Mutex;
use embassy_usb::Builder as UsbBuilder;
use embassy_usb_dfu::consts::DfuAttributes;
use embassy_usb_dfu::dfu::new_state;
use embassy_usb_dfu::ResetImmediate;

use core::cell::RefCell;
use defmt::*;
use defmt_rtt as _;
use panic_probe as _;

// ── USB interrupt binding ──────────────────────────────────────────────────

bind_interrupts!(struct Irqs {
    OTG_HS => usb::InterruptHandler<peripherals::USB_OTG_HS>;
});

// ── Flash write granularity for STM32H7 ───────────────────────────────────
// STM32H7 flash write size is 32 bytes (256-bit word).
// Used for the STATE aligned buffer passed to BlockingFirmwareUpdater.
const FLASH_WRITE_SIZE: usize = 32;
// DFU USB transfer block size — must be a multiple of FLASH_WRITE_SIZE.
// 64 bytes matches dfu-util's minimum transfer size and the host's DFU_BLOCK_SIZE.
const DFU_BLOCK_SIZE: usize = 64;

// ── Ed25519 public key ─────────────────────────────────────────────────────
// The 32-byte verifying key is compiled in from firmware/signing-pubkey.bin.
// Replace signing-pubkey.bin with the real public key before production use.
// Rotating the key requires reflashing this bootloader via JTAG.
static PUBLIC_KEY: [u8; 32] = *include_bytes!("../../signing-pubkey.bin");

// Bootloader version constants (BL_MAJ, BL_MIN, BL_PAT) — generated by build.rs.
mod version {
    include!(concat!(env!("OUT_DIR"), "/version_consts.rs"));
}

// ── USB descriptor static buffers ─────────────────────────────────────────
static mut CONFIG_DESC: [u8; 256] = [0u8; 256];
static mut BOS_DESC: [u8; 256] = [0u8; 256];
static mut MSOS_DESC: [u8; 256] = [0u8; 256];
static mut CTRL_BUF: [u8; 64] = [0u8; 64];
static mut USB_EP_OUT_BUF: [u8; 1024] = [0u8; 1024];

// ── Entry point ────────────────────────────────────────────────────────────

#[embassy_executor::main]
async fn main(_spawner: Spawner) {
    // ── Disable D-cache (USB DMA coherency) ──────────────────────────────────
    unsafe {
        let mut cp = cortex_m::peripheral::Peripherals::steal();
        cp.SCB.disable_dcache(&mut cp.CPUID);
    }

    // ── Clock configuration (minimal — enough for flash + USB) ───────────────
    // Same PLL1 400 MHz + HSI48 USB as the app, but no FDCAN/TIM2.
    let mut config = Config::default();
    {
        use embassy_stm32::rcc::*;
        config.rcc.hse = Some(Hse {
            freq: embassy_stm32::time::Hertz(25_000_000),
            mode: HseMode::Oscillator,
        });
        config.rcc.pll1 = Some(Pll {
            source: PllSource::HSE,
            prediv: PllPreDiv::DIV5,
            mul: PllMul::MUL160,
            divp: Some(PllDiv::DIV2),
            divq: None,
            divr: None,
            fracn: None,
        });
        config.rcc.sys = Sysclk::PLL1_P;
        config.rcc.ahb_pre = AHBPrescaler::DIV2;
        config.rcc.apb1_pre = APBPrescaler::DIV2;
        config.rcc.apb2_pre = APBPrescaler::DIV2;
        config.rcc.apb3_pre = APBPrescaler::DIV2;
        config.rcc.apb4_pre = APBPrescaler::DIV2;
        config.rcc.voltage_scale = VoltageScale::Scale1;
        config.rcc.csi = true;
        config.rcc.hsi48 = Some(Hsi48Config {
            sync_from_usb: false,
        });
        config.rcc.mux.usbsel = mux::Usbsel::HSI48;
    }
    let p = embassy_stm32::init(config);

    // ── LED: LD1 (green, PF10) — solid on = DFU mode, blink = boot swap ───────
    let mut led = Output::new(p.PF10, Level::High, Speed::Low);

    // ── Flash via embassy-boot partitions ──────────────────────────────────────
    let flash = Flash::new_blocking(p.FLASH);
    let flash_mutex: Mutex<NoopRawMutex, RefCell<Flash<'_, Blocking>>> =
        Mutex::new(RefCell::new(flash));

    // ── embassy-boot: prepare (swap if updated, revert if unconfirmed) ─────────
    // BootLoader::prepare runs the swap / revert logic synchronously.
    // If there is a verified update staged, it copies DFU → Active here.
    // If the previous update was not confirmed (mark_booted not called), it reverts.
    // After prepare, the Active partition always contains the best valid image.
    {
        use embassy_boot_stm32::BootLoaderConfig;
        let bl_config =
            BootLoaderConfig::from_linkerfile_blocking(&flash_mutex, &flash_mutex, &flash_mutex);
        let bl = BootLoader::prepare::<_, _, _, FLASH_WRITE_SIZE>(bl_config);
        info!("BootLoader state after prepare: {:?}", bl.state);

        // Check whether the bootloader was asked to enter DFU download mode.
        // embassy-usb-dfu (application feature) sets State::DfuDetach in the
        // STATE partition when the app receives a DFU_DETACH request.
        // We detect this here and start the USB DFU stack instead of jumping.
        use embassy_boot::State;
        if bl.state != State::DfuDetach {
            // Normal boot: no staged update or update already applied → jump.
            info!("Jumping to app at 0x08020000");
            // Stamp the bootloader version into RTC backup registers before the
            // jump so the app can read and display it on the LCD header row.
            // BKP1R: packed version  (major<<16 | minor<<8 | patch)
            // BKP2R: sentinel 0xB007_B007 confirming a valid bootloader handoff
            {
                use embassy_stm32::pac;
                pac::PWR.cr1().modify(|w| w.set_dbp(true));
                let v = (version::BL_MAJ as u32) << 16
                    | (version::BL_MIN as u32) << 8
                    | version::BL_PAT as u32;
                pac::RTC.bkpr(1).write(|w| w.set_bkp(v));
                pac::RTC.bkpr(2).write(|w| w.set_bkp(0xB007_B007));
            }
            led.set_low();

            // ── USB OTG HS PHY disconnect before jumping ─────────────────────
            // The USB3320C ULPI PHY is an external device that survives NVIC
            // soft-reset.  After a DFU session it keeps D+ asserted via its
            // internal 1.5 kΩ pull-up; the host never sees a disconnect, so it
            // ignores the app's re-enumeration.
            //
            // Fix: enable the OTG HS + ULPI clocks (they are off here), then
            // assert the RCC peripheral reset.  With the clocks running the
            // OTG core asserts PHY_RST on the ULPI bus, which drives the
            // USB3320C RESET# pin low → PHY returns to power-on state with all
            // pull-ups disabled → D+ goes low → host sees SE0 → disconnect.
            // Finally disable the clocks before jumping so the app can claim
            // the peripheral cleanly.
            {
                use embassy_stm32::pac;
                // 1. Enable OTG HS + ULPI clocks
                pac::RCC.ahb1enr().modify(|w| {
                    w.set_usb_otg_hsen(true);
                    w.set_usb_otg_hs_ulpien(true);
                });
                cortex_m::asm::delay(200_000); // ~1 ms — let clocks stabilise

                // 2. Assert peripheral reset (propagates PHY_RST to USB3320C)
                pac::RCC.ahb1rstr().modify(|w| w.set_usb_otg_hsrst(true));
                cortex_m::asm::delay(600_000); // ~3 ms — host detects SE0

                // 3. Release reset; PHY is now in default state (no pull-ups)
                pac::RCC.ahb1rstr().modify(|w| w.set_usb_otg_hsrst(false));
                cortex_m::asm::delay(200_000); // ~1 ms settle

                // 4. Disable clocks so the app peripheral init starts clean
                pac::RCC.ahb1enr().modify(|w| {
                    w.set_usb_otg_hsen(false);
                    w.set_usb_otg_hs_ulpien(false);
                });
            }

            // SAFETY: app is a valid Cortex-M image at the Active partition start.
            unsafe { bl.load(0x08020000) }
        }
        // else: DFU mode requested — fall through to USB DFU stack below.
    }

    info!("Entering USB DFU download mode");

    // ── Firmware updater for DFU download ─────────────────────────────────────
    let updater_config =
        FirmwareUpdaterConfig::from_linkerfile_blocking(&flash_mutex, &flash_mutex);
    let mut aligned = AlignedBuffer([0u8; FLASH_WRITE_SIZE]);
    let updater = BlockingFirmwareUpdater::new(updater_config, aligned.as_mut());

    // ── USB OTG HS (ULPI, USB3320C-EZK) ───────────────────────────────────────
    let mut usb_cfg = embassy_stm32::usb::Config::default();
    usb_cfg.vbus_detection = false;
    // SAFETY: static mut buffers, main() called once.
    let driver = Driver::new_hs_ulpi(
        p.USB_OTG_HS,
        Irqs,
        p.PA5,  // ULPI_CLK
        p.PI11, // ULPI_DIR
        p.PH4,  // ULPI_NXT
        p.PC0,  // ULPI_STP
        p.PA3,
        p.PB0,
        p.PB1,
        p.PB10,
        p.PB11,
        p.PB12,
        p.PB13,
        p.PB5,
        unsafe { &mut *core::ptr::addr_of_mut!(USB_EP_OUT_BUF) },
        usb_cfg,
    );

    let mut usb_config = embassy_usb::Config::new(0x1209, 0xBEEF);
    usb_config.manufacturer = Some("Kodezine");
    usb_config.product = Some("KCAN DFU H743");
    usb_config.serial_number = Some("00000000");
    usb_config.max_power = 100;
    usb_config.max_packet_size_0 = 64;
    usb_config.composite_with_iads = false;
    usb_config.device_class = 0xFE; // Application Specific
    usb_config.device_sub_class = 0x01; // Device Firmware Upgrade
    usb_config.device_protocol = 0x02; // DFU mode

    // DFU state must outlive the builder.
    let mut dfu_state = new_state::<_, _, _, DFU_BLOCK_SIZE>(
        updater,
        DfuAttributes::CAN_DOWNLOAD, // No MANIFESTATION_TOLERANT — device resets via ResetImmediate after flash
        ResetImmediate,
        &PUBLIC_KEY,
    );

    // SAFETY: static mut descriptor buffers, initialised once.
    // SAFETY: static mut buffers, main() runs once, no other references.
    let mut builder = unsafe {
        UsbBuilder::new(
            driver,
            usb_config,
            &mut *core::ptr::addr_of_mut!(CONFIG_DESC),
            &mut *core::ptr::addr_of_mut!(BOS_DESC),
            &mut *core::ptr::addr_of_mut!(MSOS_DESC),
            &mut *core::ptr::addr_of_mut!(CTRL_BUF),
        )
    };

    embassy_usb_dfu::dfu::usb_dfu(&mut builder, &mut dfu_state, |_| {});

    let mut usb = builder.build();

    info!("USB DFU: waiting for host to send firmware");
    usb.run().await;
    // After a completed DFU_MANIFESTATION the device auto-resets (ResetImmediate).
}
