settings:
  digits: 3
  prefix: SOUP
  sep: ''
  itemformat: markdown
attributes:
  defaults:
    doc:
      title: RustyCAN — Software of Unknown Provenance (SOUP)
      copyright: RustyCAN
    type: functional
    iec62304-clause: '8.1.2'
  reviewed:
    - type
    - iec62304-clause
  publish:
    - type
    - iec62304-clause
