//! build.rs — generates compile-time assets for the lcd-terminal crate.
//!
//! Outputs written to OUT_DIR:
//!   - `ibm_cp437_1bpp.rs`  — `[[u8;16]; 256]` literal of VGA 8×16 1bpp bitmaps
//!   - `lcd_handoff.x`      — linker snippet for `.lcd_handoff` NOLOAD section

use std::env;
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());

    gen_font_table(&out);
    gen_icon_rgb565(&out);
    gen_linker_script(&out);

    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=ibm_cp437_8x16.bin");
    println!("cargo:rerun-if-changed=../../host/assets/RustyCAN.iconset/icon_128x128.png");
}

/// Read the 4 096-byte binary font dump and emit a Rust literal.
fn gen_font_table(out: &Path) {
    // 256 glyphs × 16 bytes.  Each byte = one scan-line, MSB = leftmost pixel.
    // The .bin file is the public-domain IBM CP437 VGA 8×16 ROM font.
    let src = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("ibm_cp437_8x16.bin");
    let raw = fs::read(&src).expect("ibm_cp437_8x16.bin not found — see firmware/lcd-terminal/");
    assert_eq!(
        raw.len(),
        256 * 16,
        "expected exactly 4096 bytes in ibm_cp437_8x16.bin"
    );

    let mut s = String::from("[\n");
    for g in 0..256usize {
        s.push_str("    [");
        for b in 0..16usize {
            write!(s, "0x{:02X},", raw[g * 16 + b]).unwrap();
        }
        s.push_str("],\n");
    }
    s.push(']');
    fs::write(out.join("ibm_cp437_1bpp.rs"), s).expect("write ibm_cp437_1bpp.rs");
}

/// Convert icon_128x128.png → packed RGB565 Rust array literal.
///
/// Alpha is pre-multiplied against a black background so transparent regions
/// render as black on the LCD.  Output file: `$OUT_DIR/icon_128x128_rgb565.rs`.
fn gen_icon_rgb565(out: &Path) {
    let src = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../../host/assets/RustyCAN.iconset/icon_128x128.png");

    let img = image::open(&src)
        .expect("icon_128x128.png not found — expected at host/assets/RustyCAN.iconset/")
        .into_rgba8();

    assert_eq!(img.width(), 128, "icon must be 128 pixels wide");
    assert_eq!(img.height(), 128, "icon must be 128 pixels tall");

    let mut s = String::with_capacity(128 * 128 * 9);
    s.push('[');
    for pixel in img.pixels() {
        let a = pixel[3] as u32;
        // Pre-multiply alpha against black (just scale each channel).
        let r = ((pixel[0] as u32 * a) / 255) as u16;
        let g = ((pixel[1] as u32 * a) / 255) as u16;
        let b = ((pixel[2] as u32 * a) / 255) as u16;
        let rgb565: u16 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
        write!(s, "0x{:04X}_u16,", rgb565).unwrap();
    }
    s.push(']');
    fs::write(out.join("icon_128x128_rgb565.rs"), s).expect("write icon_128x128_rgb565.rs");
}

/// Write the linker script that places .lcd_handoff (NOLOAD) in SRAM4.
fn gen_linker_script(out: &Path) {
    fs::write(
        out.join("lcd_handoff.x"),
        r#"/* lcd_handoff.x  — generated by lcd-terminal/build.rs
 *
 * Places .lcd_handoff as a NOLOAD section at the base of SRAM4 (0x38000000).
 * cortex-m-rt never zeroes NOLOAD sections, so LcdHandoff survives
 * a software reset / bootloader->firmware jump.
 *
 * Uses an explicit absolute VMA instead of "> SRAM4" because rust-lld does
 * not reliably honour memory-region assignments inside INSERT BEFORE blocks.
 */
SECTIONS {
    .lcd_handoff 0x38000000 (NOLOAD) :
    {
        KEEP(*(.lcd_handoff .lcd_handoff.*));
    }
} INSERT BEFORE .bss;
"#,
    )
    .expect("write lcd_handoff.x");
}
