//! KCAN EP0 vendor request handler.
//!
//! Responds to the control sequence the host KCAN adapter issues on every
//! connect before bulk traffic can start:
//!
//! ```text
//! Host → GET_INFO      (0x01)  device responds with firmware version + UID
//! Host → GET_BT_CONST  (0x06)  device responds with clock / BRP / TSEG limits
//! Host → SET_BITTIMING (0x02)  host sends computed BRP/TSEG for chosen bitrate
//! Host → SET_MODE      (0x04)  host sends bus-on / listen-only flags
//! ```
//!
//! Without this handler `KCanAdapter::open()` fails immediately with
//! `"GET_INFO: short response"` and no bulk traffic flows.
//!
//! This handler also drives [`crate::usb_task::USB_CONFIGURED`] on connect /
//! disconnect (replacing the old `UsbStateHandler`), so only one handler needs
//! to be registered with the USB builder.

use embassy_usb::control::{InResponse, OutResponse, Recipient, Request, RequestType};
use embassy_usb::Handler;

use kcan_protocol::control::{
    KCanBitTiming, KCanBtConst, KCanDeviceInfo, KCanFdConfig, KCanMode, KCanModeFdFlags,
    KCanModeFlags, RequestCode,
};

use defmt::*;

// Firmware version constants generated by build.rs.
mod version {
    include!(concat!(env!("OUT_DIR"), "/version_consts.rs"));
}

// ─── Pending bit-timing storage ───────────────────────────────────────────────
use core::cell::Cell;
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::blocking_mutex::Mutex;

static PENDING_NOMINAL_BT: Mutex<CriticalSectionRawMutex, Cell<Option<KCanBitTiming>>> =
    Mutex::new(Cell::new(None));

static PENDING_FD_BT: Mutex<CriticalSectionRawMutex, Cell<Option<KCanBitTiming>>> =
    Mutex::new(Cell::new(None));

/// EP0 vendor handler: responds to GET_INFO / GET_BT_CONST and ACKs
/// SET_BITTIMING / SET_MODE.  Also signals USB connection state.
pub struct KCanEp0Handler {
    pub uid_lo: u32,
}

impl Handler for KCanEp0Handler {
    fn configured(&mut self, configured: bool) {
        if configured {
            info!("USB: configured by host");
        } else {
            info!("USB: disconnected / reset");
        }
        crate::usb_task::USB_CONFIGURED.signal(configured);
        crate::usb_task::USB_CONFIGURED_LED.signal(configured);
    }

    fn control_in<'a>(&'a mut self, req: Request, buf: &'a mut [u8]) -> Option<InResponse<'a>> {
        // Only intercept vendor requests directed at the device.
        if req.request_type != RequestType::Vendor || req.recipient != Recipient::Device {
            return None;
        }

        match req.request {
            r if r == RequestCode::GetInfo as u8 => {
                let mut info = KCanDeviceInfo::new(
                    version::FW_MAJ,
                    version::FW_MIN,
                    version::FW_PAT,
                    self.uid_lo,
                );
                // H753 exposes two FDCAN channels; frames carry a channel field.
                info.channels = 2;
                let bytes = info.to_bytes();
                let len = bytes.len().min(buf.len());
                buf[..len].copy_from_slice(&bytes[..len]);
                info!(
                    "EP0 GET_INFO → protocol_v1, channels=2, uid={:08X}",
                    self.uid_lo
                );
                Some(InResponse::Accepted(&buf[..len]))
            }
            r if r == RequestCode::GetBtConst as u8 => {
                let bytes = KCanBtConst::H753_32MHZ.to_bytes();
                let len = bytes.len().min(buf.len());
                buf[..len].copy_from_slice(&bytes[..len]);
                info!("EP0 GET_BT_CONST → clock=32 MHz, BRP 1-512");
                Some(InResponse::Accepted(&buf[..len]))
            }
            _ => None,
        }
    }

    fn control_out(&mut self, req: Request, _data: &[u8]) -> Option<OutResponse> {
        // Only intercept vendor requests directed at the device.
        if req.request_type != RequestType::Vendor || req.recipient != Recipient::Device {
            return None;
        }

        match req.request {
            r if r == RequestCode::SetBitTiming as u8 => {
                if let Some(bt) = _data
                    .get(..16)
                    .and_then(|s| <&[u8; 16]>::try_from(s).ok())
                    .map(KCanBitTiming::from_bytes)
                {
                    let (brp, tseg1, tseg2) = (bt.brp, bt.tseg1, bt.tseg2);
                    let tq = 1 + tseg1 + tseg2;
                    if brp > 0 && tq > 0 {
                        let kbps = KCanBtConst::H753_32MHZ.clock_hz / (brp * tq) / 1_000;
                        info!("EP0 SET_BITTIMING → {} kbps", kbps);
                    }
                    PENDING_NOMINAL_BT.lock(|c| c.set(Some(bt)));
                } else {
                    info!("EP0 SET_BITTIMING accepted");
                }
                Some(OutResponse::Accepted)
            }
            r if r == RequestCode::SetFdBitTiming as u8 => {
                if let Some(bt) = _data
                    .get(..16)
                    .and_then(|s| <&[u8; 16]>::try_from(s).ok())
                    .map(KCanBitTiming::from_bytes)
                {
                    let (brp, tseg1, tseg2, sjw) = (bt.brp, bt.tseg1, bt.tseg2, bt.sjw);
                    info!(
                        "EP0 SET_FD_BITTIMING → BRP={} TSEG1={} TSEG2={} SJW={}",
                        brp, tseg1, tseg2, sjw
                    );
                    PENDING_FD_BT.lock(|c| c.set(Some(bt)));
                } else {
                    info!("EP0 SET_FD_BITTIMING: invalid payload");
                }
                Some(OutResponse::Accepted)
            }
            r if r == RequestCode::SetMode as u8 => {
                let (flags, fd_flags) = if _data.len() >= 4 {
                    let arr: [u8; 4] = _data[..4].try_into().unwrap();
                    let m = KCanMode::from_bytes(&arr);
                    (m.flags, m.fd_flags)
                } else if !_data.is_empty() {
                    (_data[0], 0u8)
                } else {
                    (0u8, 0u8)
                };

                if flags & KCanModeFlags::BUS_OFF != 0 {
                    info!("EP0 SET_MODE bus-off (app closed)");
                    crate::usb_task::LISTEN_ONLY
                        .store(false, core::sync::atomic::Ordering::Relaxed);
                } else {
                    let listen_only = flags & KCanModeFlags::LISTEN_ONLY != 0;
                    crate::usb_task::LISTEN_ONLY
                        .store(listen_only, core::sync::atomic::Ordering::Relaxed);

                    let nominal_baud = PENDING_NOMINAL_BT
                        .lock(|c| c.get())
                        .and_then(|bt| {
                            let tq = 1 + bt.tseg1 + bt.tseg2;
                            if bt.brp > 0 && tq > 0 {
                                Some(KCanBtConst::H753_32MHZ.clock_hz / (bt.brp * tq))
                            } else {
                                None
                            }
                        })
                        .unwrap_or(250_000);

                    let fd_enabled = fd_flags & KCanModeFdFlags::FD_ENABLED != 0;
                    let fd_timing = if fd_enabled {
                        PENDING_FD_BT.lock(|c| c.get())
                    } else {
                        None
                    };
                    let iso = fd_flags & KCanModeFdFlags::NON_ISO == 0;

                    let cfg = KCanFdConfig {
                        nominal_baud,
                        fd_timing,
                        iso,
                        mode_flags: flags,
                    };
                    // Send one copy per FDCAN channel (pool_size = 2).
                    let _ = crate::usb_task::CAN_CONFIG.try_send(cfg);
                    let _ = crate::usb_task::CAN_CONFIG.try_send(cfg);

                    if listen_only {
                        info!(
                            "EP0 SET_MODE bus-on (listen-only, {} bps, fd={})",
                            nominal_baud, fd_enabled
                        );
                    } else {
                        info!(
                            "EP0 SET_MODE bus-on ({} bps, fd={})",
                            nominal_baud, fd_enabled
                        );
                    }
                    crate::usb_task::BULK_RESTART.signal(());
                }
                Some(OutResponse::Accepted)
            }
            _ => None,
        }
    }
}
